/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.vadmin;

import bbdd.Conexion;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco Antonio
 */
public class PrincipalAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName());

    /**
     * Creates new form PrincipalAdmin
     */
    public PrincipalAdmin() {
        initComponents();
        DefaultTableModel modeloTablaMenu = (DefaultTableModel) tbUltimosArticulos.getModel();
        Conexion.ObtenerUltimosTresArticulos(modeloTablaMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btnOpcionUno = new javax.swing.JButton();
        btnOpcionDos = new javax.swing.JButton();
        btnOpcionTres = new javax.swing.JButton();
        btnOpcionCuatro = new javax.swing.JButton();
        btnOpcionCinco = new javax.swing.JButton();
        btnOpcionSeis = new javax.swing.JButton();
        btnOpcionSiete = new javax.swing.JButton();
        btnOpcionOcho = new javax.swing.JButton();
        btnOpcionNueve = new javax.swing.JButton();
        btnOpcionDiez = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbUltimosArticulos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuVer = new javax.swing.JMenu();
        miTotalArticulos = new javax.swing.JMenuItem();
        miArticulosDestacados = new javax.swing.JMenuItem();
        miArticulosOferta = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenu();
        miMantUsuarios = new javax.swing.JMenuItem();
        miMantCategoria = new javax.swing.JMenuItem();
        miMantOrigenes = new javax.swing.JMenuItem();
        miMantTiendas = new javax.swing.JMenuItem();
        menuRegistro = new javax.swing.JMenu();
        miRegistoArticulos = new javax.swing.JMenuItem();
        miRegistroUsuarios = new javax.swing.JMenuItem();
        menuOpciones = new javax.swing.JMenu();
        miDatosCuenta = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FERRETERIA MONTOYA - Menú de administrador");
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(255, 0, 0));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_ferreteria_150_82.png"))); // NOI18N

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("Bienvenido Administrador");

        panelPrincipal.setBackground(new java.awt.Color(0, 0, 0));

        panelBotones.setBackground(new java.awt.Color(255, 255, 0));
        panelBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOpcionUno.setText("Ver listado total de articulos");
        btnOpcionUno.addActionListener(this::btnOpcionUnoActionPerformed);
        panelBotones.add(btnOpcionUno);

        btnOpcionDos.setText("Ver listado de artículos en oferta");
        btnOpcionDos.addActionListener(this::btnOpcionDosActionPerformed);
        panelBotones.add(btnOpcionDos);

        btnOpcionTres.setText("Ver listado de artículos deseados");
        btnOpcionTres.addActionListener(this::btnOpcionTresActionPerformed);
        panelBotones.add(btnOpcionTres);

        btnOpcionCuatro.setText("Mantenimiento de Usuarios");
        btnOpcionCuatro.addActionListener(this::btnOpcionCuatroActionPerformed);
        panelBotones.add(btnOpcionCuatro);

        btnOpcionCinco.setText("Mantenimiento de Categorias");
        btnOpcionCinco.addActionListener(this::btnOpcionCincoActionPerformed);
        panelBotones.add(btnOpcionCinco);

        btnOpcionSeis.setText("Mantenimiento de Origenes");
        btnOpcionSeis.addActionListener(this::btnOpcionSeisActionPerformed);
        panelBotones.add(btnOpcionSeis);

        btnOpcionSiete.setText("Mantenimiento de Tiendas");
        btnOpcionSiete.addActionListener(this::btnOpcionSieteActionPerformed);
        panelBotones.add(btnOpcionSiete);

        btnOpcionOcho.setText("Registro de Artículos");
        btnOpcionOcho.addActionListener(this::btnOpcionOchoActionPerformed);
        panelBotones.add(btnOpcionOcho);

        btnOpcionNueve.setText("Registro de Usuarios");
        btnOpcionNueve.addActionListener(this::btnOpcionNueveActionPerformed);
        panelBotones.add(btnOpcionNueve);

        btnOpcionDiez.setText("Ver datos de su Cuenta");
        btnOpcionDiez.addActionListener(this::btnOpcionDiezActionPerformed);
        panelBotones.add(btnOpcionDiez);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tabla de últimos tres articulos agregados:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Menú de Opciones");

        tbUltimosArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Categoría", "Precio venta", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbUltimosArticulos);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 510, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagen)
                .addContainerGap())
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        menuVer.setText("Ver");

        miTotalArticulos.setText("Total de artículos");
        miTotalArticulos.addActionListener(this::miTotalArticulosActionPerformed);
        menuVer.add(miTotalArticulos);

        miArticulosDestacados.setText("Artículos deseados");
        miArticulosDestacados.addActionListener(this::miArticulosDestacadosActionPerformed);
        menuVer.add(miArticulosDestacados);

        miArticulosOferta.setText("Artículos en oferta");
        miArticulosOferta.addActionListener(this::miArticulosOfertaActionPerformed);
        menuVer.add(miArticulosOferta);

        jMenuBar1.add(menuVer);

        menuMantenimiento.setText("Mantenimiento");

        miMantUsuarios.setText("Usuarios");
        miMantUsuarios.addActionListener(this::miMantUsuariosActionPerformed);
        menuMantenimiento.add(miMantUsuarios);

        miMantCategoria.setText("Categorias");
        miMantCategoria.addActionListener(this::miMantCategoriaActionPerformed);
        menuMantenimiento.add(miMantCategoria);

        miMantOrigenes.setText("Origenes");
        miMantOrigenes.addActionListener(this::miMantOrigenesActionPerformed);
        menuMantenimiento.add(miMantOrigenes);

        miMantTiendas.setText("Tiendas");
        miMantTiendas.addActionListener(this::miMantTiendasActionPerformed);
        menuMantenimiento.add(miMantTiendas);

        jMenuBar1.add(menuMantenimiento);

        menuRegistro.setText("Registros");

        miRegistoArticulos.setText("Registrar artículos");
        miRegistoArticulos.addActionListener(this::miRegistoArticulosActionPerformed);
        menuRegistro.add(miRegistoArticulos);

        miRegistroUsuarios.setText("Registrar usuarios");
        miRegistroUsuarios.addActionListener(this::miRegistroUsuariosActionPerformed);
        menuRegistro.add(miRegistroUsuarios);

        jMenuBar1.add(menuRegistro);

        menuOpciones.setText("Opciones");

        miDatosCuenta.setText("Mis datos");
        miDatosCuenta.addActionListener(this::miDatosCuentaActionPerformed);
        menuOpciones.add(miDatosCuenta);

        miSalir.setText("Salir");
        miSalir.addActionListener(this::miSalirActionPerformed);
        menuOpciones.add(miSalir);

        jMenuBar1.add(menuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcionOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionOchoActionPerformed
        RegistroArticulos v = new RegistroArticulos(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_btnOpcionOchoActionPerformed

    private void btnOpcionNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionNueveActionPerformed
        RegistroUsuarios v = new RegistroUsuarios(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_btnOpcionNueveActionPerformed

    private void btnOpcionDiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionDiezActionPerformed
        DatosCuentas v = new DatosCuentas(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_btnOpcionDiezActionPerformed

    private void btnOpcionCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionCuatroActionPerformed
        MantUsuarios v = new MantUsuarios(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_btnOpcionCuatroActionPerformed

    private void btnOpcionCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionCincoActionPerformed
        MantCategorias v = new MantCategorias(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_btnOpcionCincoActionPerformed

    private void btnOpcionSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionSeisActionPerformed
        MantOrigenes v = new MantOrigenes(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_btnOpcionSeisActionPerformed

    private void btnOpcionSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionSieteActionPerformed
        MantTiendas v = new MantTiendas(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_btnOpcionSieteActionPerformed

    private void btnOpcionUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionUnoActionPerformed
        ListaArticulo v = new ListaArticulo(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_btnOpcionUnoActionPerformed

    private void btnOpcionDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionDosActionPerformed
        ListaArticulosOferta v = new ListaArticulosOferta(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_btnOpcionDosActionPerformed

    private void btnOpcionTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionTresActionPerformed
        ListaArticulosDestacados v = new ListaArticulosDestacados(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_btnOpcionTresActionPerformed

    private void miTotalArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTotalArticulosActionPerformed
        // Menu Item - Ver - Total de artículos
        ListaArticulo v = new ListaArticulo(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_miTotalArticulosActionPerformed

    private void miArticulosDestacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miArticulosDestacadosActionPerformed
        // Menu Item - Ver -  Artículos Destacados
        ListaArticulosDestacados v = new ListaArticulosDestacados(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_miArticulosDestacadosActionPerformed

    private void miArticulosOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miArticulosOfertaActionPerformed
        // Menu Item - Ver -  Artículos Oferta
        ListaArticulosOferta v = new ListaArticulosOferta(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_miArticulosOfertaActionPerformed

    private void miMantUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMantUsuariosActionPerformed
        // Menu Item - Mantenimiento - MantUsuarios
        MantUsuarios v = new MantUsuarios(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_miMantUsuariosActionPerformed

    private void miMantCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMantCategoriaActionPerformed
        // Menu Item - Mantenimiento - MantCategoria
        MantCategorias v = new MantCategorias(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_miMantCategoriaActionPerformed

    private void miMantOrigenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMantOrigenesActionPerformed
        // Menu Item - Mantenimiento - MantOrigenes
        MantOrigenes v = new MantOrigenes(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_miMantOrigenesActionPerformed

    private void miMantTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMantTiendasActionPerformed
        // Menu Item - Mantenimiento - MantTiendas
        MantTiendas v = new MantTiendas(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_miMantTiendasActionPerformed

    private void miRegistoArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistoArticulosActionPerformed
        // Menu Item - Registro - RegistroArticulo
        RegistroArticulos v = new RegistroArticulos(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_miRegistoArticulosActionPerformed

    private void miRegistroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistroUsuariosActionPerformed
        // Menu Item - Registro - RegistroUsuarios
        RegistroUsuarios v = new RegistroUsuarios(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_miRegistroUsuariosActionPerformed

    private void miDatosCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDatosCuentaActionPerformed
        // Menu Item - Opciones - Mis datos
        DatosCuentas v = new DatosCuentas(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_miDatosCuentaActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        // Menú Item - Opciones - Salir
        System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrincipalAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpcionCinco;
    private javax.swing.JButton btnOpcionCuatro;
    private javax.swing.JButton btnOpcionDiez;
    private javax.swing.JButton btnOpcionDos;
    private javax.swing.JButton btnOpcionNueve;
    private javax.swing.JButton btnOpcionOcho;
    private javax.swing.JButton btnOpcionSeis;
    private javax.swing.JButton btnOpcionSiete;
    private javax.swing.JButton btnOpcionTres;
    private javax.swing.JButton btnOpcionUno;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenu menuRegistro;
    private javax.swing.JMenu menuVer;
    private javax.swing.JMenuItem miArticulosDestacados;
    private javax.swing.JMenuItem miArticulosOferta;
    private javax.swing.JMenuItem miDatosCuenta;
    private javax.swing.JMenuItem miMantCategoria;
    private javax.swing.JMenuItem miMantOrigenes;
    private javax.swing.JMenuItem miMantTiendas;
    private javax.swing.JMenuItem miMantUsuarios;
    private javax.swing.JMenuItem miRegistoArticulos;
    private javax.swing.JMenuItem miRegistroUsuarios;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JMenuItem miTotalArticulos;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tbUltimosArticulos;
    // End of variables declaration//GEN-END:variables
}
